on:
  push:
  schedule:
    - cron: "38 23 * * *" #早上7点45左右推送
  workflow_dispatch:
    
jobs:
  bot:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4.1.7
      - name: Install Node.js
        uses: actions/setup-node@v4.0.3
      - name: Use Node.js version 20.x
        run: |
          sudo npm install -g n
          sudo n 18
      - name: python env
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.8
      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install bs4
          pip install requests
      - name: 'Get DataSource'
        run: curl https://news.topurl.cn > ./result.html
      - name: 'Get Info'
        run: python ./getInfo.py
      - name: 'Get Date'
        run: |
          echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
          echo "TODAY_DATE=$(TZ=':Asia/Shanghai' date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: 'Get TEXT'
        run: |
            echo 'FILE_TEXT<<EOF' >> $GITHUB_ENV
            cat ./result.txt >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
            echo secrets.WECHATQUN_WEBHOOK

#       - name: 'Send mail'
#         uses: dawidd6/action-send-mail@master
#         with:
#           server_address: smtp.163.com
#           server_port: 465
#           username: ${{ secrets.MAIL_USER_NMAE }}
#           password: ${{ secrets.MAIL_PWD }}
#           subject: 今日新闻简报推送 (${{env.REPORT_DATE}})
#           body: file://result.txt
#           to: 1129159201@qq.com
#           from: GitHub Actions
#           content_type: text/html
            
      # - name: '企业微信webhook'
      #   uses: MeanZhang/wecom-group-robot@v1.2
      #   with:
      #       key: ${{ secrets.WECOM_WEBHOOK_KEY }}
      #       msgtype: text
      #       content: ${{ env.FILE_TEXT }}

      # - name: '发送到中间件'
      #   uses: chf007/action-wechat-work@master
      #   with:
      #     msgtype: text
      #     content: |
      #       ${{env.FILE_TEXT}}
      #   env:
      #     WECHAT_WORK_BOT_WEBHOOK: ${{ secrets.WECHATQUN_WEBHOOK }}

      # - name: '发送到TG频道'
      #   run: |
      #     python send_to_telegram.py
      #   env:
      #     TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      #     TELEGRAM_CHANNEL_ID: -1001436520490
                     
      - name: '打完收工,提交代码!'
        run: |
          git config --local user.email "356480127@qq.com"
          git config --local user.name ${{ secrets.GIT_NAME }}
          git remote set-url origin https://${{ github.actor }}:${{ secrets.MYGG_TOKEN }}@github.com/${{ github.repository }}
          git pull 
          cp -Rf result.txt logs/${{env.TODAY_DATE}}.txt
          git add .
          git commit -m "Update By Github Action Bot"
          git push
